# Generated by Django 4.0.3 on 2022-03-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
