# Generated by Django 4.0.3 on 2022-03-23 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_invitation_unique_invite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='Приглашающий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный'),
        ),
    ]
